 <!-- Modernizer JS -->
 <script src="{{ asset('frontend/assets/js/vendor/modernizr.min.js') }}"></script>
 <!-- jQuery JS -->
 <script src="{{ asset('frontend/assets/js/vendor/jquery.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/bootstrap.min.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/sal.min.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/backtotop.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/magnifypopup.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/slick.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/countdown.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/jquery-appear.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/odometer.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/isotop.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/imageloaded.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/lightbox.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/wow.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/paralax.min.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/paralax-scroll.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/jquery-ui.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/tilt.jquery.min.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/alertify.min.js') }}"></script>
 <script src="{{ asset('assets/js/jquery-confirm.js') }}"></script>
 <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
 <!-- Main JS -->
 <script src="{{ asset('frontend/assets/js/main.js') }}"></script>
